# Generated by Django 6.1.1 on 2026-09-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Python Development', 'Python Development'), ('Data Analytics', 'Data Analytics'), ('Web Development', 'Web Development')], default='Web Development', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='tech',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
